---
- name: Updating apt cache
  apt:
    update_cache: yes
  become: true


- name: Installing apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
  become: true


- name: Adding google gpg key
  apt_key:
    url: "{{ GOOGLE_GPG_KEY }}"
    state: present
  become: true


- name: Adding kubectl repository
  apt_repository:
    repo: "{{ KUBECTL_REPO }}"
    state: present
    filename: kubernetes
    update_cache: yes
  become: true


- name: Installing kubectl
  apt:
    name: kubectl
    state: latest
  become: true
